name: make-test

on:
  push:
    branches:
    - "*"
  schedule:
  - cron: '42 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Run `make test`
      run: make test
